# Generated by Django 4.0.1 on 2022-10-11 15:50

import core.apps.dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nova-app', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('status', models.CharField(choices=[('bg-warning', 'Not Started'), ('bg-success', 'Running'), ('bg-info', 'Pending'), ('bg-danger', 'Stopped'), ('bg-dark', 'Terminated')], default='STOPPED', max_length=20)),
                ('stack', models.URLField(choices=[('https://cdn.discordapp.com/attachments/785734963458342973/786641902782251028/python.png', 'Python'), ('https://cdn.discordapp.com/attachments/785734963458342973/786647100749774908/node-js.png', 'Node.js'), ('https://cdn.discordapp.com/attachments/785734963458342973/786646064878845982/ruby.png', 'Ruby')], default='Python')),
                ('disk', models.IntegerField(default=0, null=True)),
                ('config', models.JSONField(default=dict)),
                ('last_deployment_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_deployment_status', models.CharField(choices=[('bg-success', 'success'), ('bg-danger', 'failed'), ('bg-warning', 'pending'), ('bg-dark', 'rejected'), ('bg-secondary', 'Not deployed')], default='Not deployed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(default='0000', max_length=5)),
                ('avatar', models.CharField(max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SlugField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to='dashboard.member')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='dashboard.member')),
                ('email_notification', models.BooleanField(default=False)),
                ('app_status_alert', models.BooleanField(default=False)),
                ('down_time_alert', models.BooleanField(default=False)),
                ('maintenance_break_alert', models.BooleanField(default=False)),
                ('display_terminated_apps', models.BooleanField(default=False)),
                ('beta_tester', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='dashboard.TeamMemberRelation', to='dashboard.Member'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('app', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='dashboard.app')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='dashboard.folder')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='dashboard.member')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_activity', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.FloatField(default=0)),
                ('item', models.FileField(null=True, upload_to=core.apps.dashboard.models.upload_location)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('system_file', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder')),
            ],
            options={
                'unique_together': {('folder', 'name')},
            },
        ),
    ]
