# Generated by Django 4.0.1 on 2022-01-11 18:25

import core.apps.dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nova-app', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('status', models.CharField(choices=[('bg-warning', 'Not Started'), ('bg-success', 'Running'), ('bg-info', 'Pending'), ('bg-danger', 'Stopped'), ('bg-dark', 'Terminated')], default='STOPPED', max_length=20)),
                ('stack', models.URLField(choices=[('https://cdn.discordapp.com/attachments/785734963458342973/786641902782251028/python.png', 'Python'), ('https://cdn.discordapp.com/attachments/785734963458342973/786647100749774908/node-js.png', 'Node.js'), ('https://cdn.discordapp.com/attachments/785734963458342973/786646064878845982/ruby.png', 'Ruby')], default='Python')),
                ('disk', models.IntegerField(default=0, null=True)),
                ('config', models.JSONField(default=dict)),
                ('last_deployment_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_deployment_status', models.CharField(choices=[('bg-success', 'success'), ('bg-danger', 'failed'), ('bg-warning', 'pending'), ('bg-dark', 'rejected'), ('bg-secondary', 'Not deployed')], default='Not deployed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(default='0000', max_length=5)),
                ('avatar', models.CharField(max_length=50, null=True)),
                ('credits', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('credits_spend', models.FloatField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('coins_redeemed', models.IntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('joined_server', models.BooleanField(default=False)),
                ('affiliate_commission', models.FloatField(default=0)),
                ('affiliate_commission_spent', models.FloatField(default=0)),
                ('first_order_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('coin_reward', models.IntegerField(default=0)),
                ('credit_reward', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.customer')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('location', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='dashboard.customer')),
                ('email_notification', models.BooleanField(default=False)),
                ('app_status_alert', models.BooleanField(default=False)),
                ('down_time_alert', models.BooleanField(default=False)),
                ('maintenance_break_alert', models.BooleanField(default=False)),
                ('new_offers_alert', models.BooleanField(default=False)),
                ('display_terminated_apps', models.BooleanField(default=False)),
                ('beta_tester', models.BooleanField(default=False)),
                ('affiliate', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('auto_dark_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('transaction_amount', models.FloatField(default=0)),
                ('payer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('payer_email', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('app', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='dashboard.app')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='dashboard.folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='applied_offers',
            field=models.ManyToManyField(blank=True, to='dashboard.Offer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.FloatField(default=0)),
                ('item', models.FileField(null=True, upload_to=core.apps.dashboard.models.upload_location)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('system_file', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder')),
            ],
            options={
                'unique_together': {('folder', 'name')},
            },
        ),
    ]
