# Generated by Django 3.1.4 on 2020-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.FloatField(choices=[(1.2, 'BASE'), (2.4, 'STANDARD'), (4.99, 'PREMIUM')]),
        ),
    ]
