# Generated by Django 4.0.1 on 2022-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberrelation',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammemberrelation',
            name='execute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammemberrelation',
            name='manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammemberrelation',
            name='read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammemberrelation',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
