# Generated by Django 4.0.1 on 2022-01-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='affiliate_commission',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='affiliate_commission_spent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='coins_redeemed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_order_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='affiliate',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='auto_dark_mode',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='dark_mode',
        ),
    ]
