# Generated by Django 3.1.4 on 2020-12-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0002_auto_20201206_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='type',
            new_name='plan',
        ),
    ]
