# Generated by Django 3.1.4 on 2020-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0003_auto_20201206_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
