# Generated by Django 4.0.1 on 2022-10-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='owner',
        ),
        migrations.AddField(
            model_name='app',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
    ]
