# Generated by Django 4.0.1 on 2022-10-06 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_teamprivilege_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='dashboard.member')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_activity', to='dashboard.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
