# Generated by Django 3.1.4 on 2020-12-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0011_customer_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tag',
            field=models.CharField(default='0000', max_length=5),
        ),
    ]
