# Generated by Django 3.1.4 on 2020-12-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0012_auto_20201210_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova_dash.customer'),
        ),
    ]
