# Generated by Django 3.1.4 on 2020-12-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0020_auto_20201210_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='_status',
            new_name='status',
        ),
    ]
