# Generated by Django 3.1.4 on 2020-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0024_auto_20201211_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='disk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='glacier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='network',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
