# Generated by Django 3.1.4 on 2020-12-16 15:37

from django.db import migrations, models
import django.db.models.deletion
import nova_dash.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0028_auto_20201216_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_dash.customer')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.FloatField(default=0)),
                ('item', models.FileField(upload_to=nova_dash.models.upload_location)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_dash.folder')),
            ],
        ),
    ]
