# Generated by Django 3.1.4 on 2020-12-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0030_folder_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='nova_dash.folder'),
        ),
    ]
