# Generated by Django 3.1.4 on 2020-12-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0031_app_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='data',
        ),
    ]
