# Generated by Django 3.1.4 on 2020-12-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0036_auto_20201221_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nova_dash.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nova_dash.customer'),
        ),
    ]
