# Generated by Django 3.1.4 on 2020-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0037_auto_20201221_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='contents',
            field=models.ManyToManyField(null=True, related_name='_folder_contents_+', to='nova_dash.Folder'),
        ),
    ]
