# Generated by Django 3.1.4 on 2020-12-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0040_auto_20201221_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
