# Generated by Django 3.1.4 on 2021-01-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0048_customer_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='nova_dash.customer')),
                ('email_notification', models.BooleanField(default=False)),
                ('app_status_alert', models.BooleanField(default=False)),
                ('down_time_alert', models.BooleanField(default=False)),
                ('maintenance_break_alert', models.BooleanField(default=False)),
                ('new_offers_alert', models.BooleanField(default=False)),
                ('ajax_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ajax_enabled',
        ),
    ]
