# Generated by Django 3.1.4 on 2021-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0049_auto_20210101_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='display_terminated_apps',
            field=models.BooleanField(default=False),
        ),
    ]
