# Generated by Django 3.1.4 on 2021-01-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0050_setting_display_terminated_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ajax_enabled',
        ),
    ]
