# Generated by Django 3.1.5 on 2021-01-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0053_auto_20210110_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('transaction_amount', models.FloatField(default=0)),
                ('payer_id', models.CharField(max_length=20)),
                ('payer_email', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nova_dash.customer')),
            ],
        ),
    ]
