# Generated by Django 3.1.5 on 2021-01-15 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0056_auto_20210113_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
