# Generated by Django 3.1.5 on 2021-01-15 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0057_app_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
