# Generated by Django 3.1.5 on 2021-01-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0058_auto_20210115_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credits_spend',
            field=models.FloatField(default=0),
        ),
    ]
