# Generated by Django 3.1.5 on 2021-02-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0064_auto_20210203_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('bg-danger', 'Failed'), ('bg-warning', 'Pending'), ('bg-success', 'Success')], max_length=15),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('bg-danger', 'Failed'), ('bg-warning', 'Pending'), ('bg-success', 'Success')], max_length=15)),
                ('failure_message', models.CharField(blank=True, max_length=120, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='nova_dash.customer')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='nova_dash.customer')),
            ],
        ),
    ]
