# Generated by Django 3.1.5 on 2021-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0068_auto_20210226_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
