# Generated by Django 3.1.5 on 2021-03-05 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0077_transaction_last_otp_generation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6393e28f-f285-4fad-9660-d18e728cc3d6'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('coin_reward', models.IntegerField(default=0)),
                ('credit_reward', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova_dash.offer')),
            ],
        ),
    ]
