# Generated by Django 3.1.5 on 2021-03-05 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0078_offer_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='applied_offers',
            field=models.ManyToManyField(blank=True, null=True, to='nova_dash.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce5a1925-7a15-486c-ba38-c8b58d0670f3'), primary_key=True, serialize=False),
        ),
    ]
