# Generated by Django 3.1.5 on 2021-03-13 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0080_auto_20210313_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
