# Generated by Django 3.1.7 on 2021-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0084_customer_joined_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='beta_tester',
            field=models.BooleanField(default=False),
        ),
    ]
