# Generated by Django 3.1.7 on 2021-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0085_setting_beta_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('bg-warning', 'Not Started'), ('bg-success', 'Running'), ('bg-info', 'Pending'), ('bg-danger', 'Stopped'), ('bg-dark', 'Terminated')], default='STOPPED', max_length=20),
        ),
    ]
