# Generated by Django 3.2 on 2021-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0092_cashoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
