# Generated by Django 3.1.5 on 2021-02-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nova_dash.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nova-app', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('status', models.CharField(choices=[('bg-warning', 'Not Started'), ('bg-success', 'Running'), ('bg-info', 'Awaiting Confirmation'), ('bg-danger', 'Stopped'), ('bg-dark', 'Terminated')], default='STOPPED', max_length=20)),
                ('stack', models.URLField(choices=[('https://cdn.discordapp.com/attachments/785734963458342973/786641902782251028/python.png', 'Python'), ('https://cdn.discordapp.com/attachments/785734963458342973/786647100749774908/node-js.png', 'Node.js'), ('https://cdn.discordapp.com/attachments/785734963458342973/786646064878845982/ruby.png', 'Ruby')], default='Python')),
                ('plan', models.FloatField(choices=[(1.2, 'Base'), (2.4, 'Standard'), (4.99, 'Premium')])),
                ('cpu', models.IntegerField(default=0, null=True)),
                ('ram', models.IntegerField(default=0, null=True)),
                ('disk', models.IntegerField(default=0, null=True)),
                ('network', models.IntegerField(default=0, null=True)),
                ('glacier', models.IntegerField(default=0, null=True)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(default='0000', max_length=5)),
                ('avatar', models.CharField(max_length=50, null=True)),
                ('credits', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('credits_spend', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nova_dash.customer')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('location', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='nova_dash.customer')),
                ('email_notification', models.BooleanField(default=False)),
                ('app_status_alert', models.BooleanField(default=False)),
                ('down_time_alert', models.BooleanField(default=False)),
                ('maintenance_break_alert', models.BooleanField(default=False)),
                ('new_offers_alert', models.BooleanField(default=False)),
                ('display_terminated_apps', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('fa-ban text-dark', 'Canceled'), ('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30)),
                ('failure_message', models.CharField(blank=True, max_length=120, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='nova_dash.customer')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='nova_dash.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_amount', models.FloatField(default=0)),
                ('payer_id', models.CharField(max_length=20)),
                ('payer_email', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='nova_dash.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('app', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='nova_dash.app')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='nova_dash.folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nova_dash.customer')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova_dash.customer'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.FloatField(default=0)),
                ('item', models.FileField(null=True, upload_to=nova_dash.models.upload_location)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('system_file', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova_dash.folder')),
            ],
            options={
                'unique_together': {('folder', 'name')},
            },
        ),
    ]
