# Generated by Django 3.1.4 on 2020-12-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0007_auto_20201208_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('bg-success', 'RUNNING'), ('bg-orange', 'PAUSED'), ('bg-info', 'STOPPED'), ('bg-danger', 'TERMINATED')], default='STOPPED', max_length=20),
        ),
    ]
