# Generated by Django 3.1.4 on 2020-12-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0008_auto_20201210_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
