# Generated by Django 3.1.4 on 2020-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0010_auto_20201210_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
