# Generated by Django 3.1.4 on 2020-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0014_app_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default='nova-app', max_length=50),
        ),
    ]
