# Generated by Django 3.1.4 on 2020-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0019_auto_20201210_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='status',
            new_name='_status',
        ),
        migrations.AddField(
            model_name='app',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
    ]
