# Generated by Django 3.1.4 on 2020-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0021_auto_20201210_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('bg-success', 'Running'), ('bg-info', 'Paused'), ('bg-danger', 'Stopped'), ('bg-muted', 'Terminated')], default='STOPPED', max_length=20),
        ),
    ]
