# Generated by Django 3.1.4 on 2020-12-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0046_customer_ajax_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='join_date',
        ),
    ]
