# Generated by Django 3.1.5 on 2021-01-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0054_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
