# Generated by Django 3.1.5 on 2021-01-23 17:48

from django.db import migrations, models
import nova_dash.models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0060_file_system_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.FileField(null=True, upload_to=nova_dash.models.upload_location),
        ),
    ]
