# Generated by Django 3.1.5 on 2021-01-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0061_auto_20210123_2318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('folder', 'name')},
        ),
    ]
