# Generated by Django 3.1.5 on 2021-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0062_auto_20210125_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='cpu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='disk',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='glacier',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='network',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='ram',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
