# Generated by Django 3.1.5 on 2021-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0063_auto_20210202_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('bg-warning', 'Not Started'), ('bg-success', 'Running'), ('bg-info', 'Awaiting Confirmation'), ('bg-danger', 'Stopped'), ('bg-dark', 'Terminated')], default='STOPPED', max_length=20),
        ),
    ]
