# Generated by Django 3.1.5 on 2021-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0067_auto_20210226_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
