# Generated by Django 3.1.5 on 2021-02-28 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0071_auto_20210228_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('fa-ban text-danger', 'Canceled'), ('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30)),
                ('failure_message', models.CharField(blank=True, max_length=120, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='nova_dash.customer')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='nova_dash.customer')),
            ],
        ),
    ]
