# Generated by Django 3.1.5 on 2021-02-28 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0071_auto_20210226_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('fa-ban text-dark', 'Canceled'), ('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30),
        ),
    ]
