# Generated by Django 3.1.5 on 2021-02-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0072_transaction'),
        ('nova_dash', '0072_auto_20210228_2122'),
    ]

    operations = [
    ]
