# Generated by Django 3.1.5 on 2021-02-28 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0073_merge_20210228_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('fa-ban text-danger', 'Canceled'), ('fa-times-circle text-danger', 'Failed'), ('fa-clock text-warning', 'Pending'), ('fa-check-circle text-success', 'Success')], max_length=30),
        ),
    ]
