# Generated by Django 3.1.5 on 2021-03-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0074_auto_20210301_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
