# Generated by Django 3.1.5 on 2021-03-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0075_auto_20210302_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
