# Generated by Django 3.1.5 on 2021-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0076_auto_20210302_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_otp_generation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
