# Generated by Django 3.1.5 on 2021-03-13 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0079_auto_20210305_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='applied_offers',
            field=models.ManyToManyField(blank=True, to='nova_dash.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c01be0f-c752-4f10-b0c2-aeedf722260b'), primary_key=True, serialize=False),
        ),
    ]
