# Generated by Django 3.1.5 on 2021-03-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0082_app_last_deployment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
