# Generated by Django 3.1.5 on 2021-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0083_customer_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined_server',
            field=models.BooleanField(default=False),
        ),
    ]
