# Generated by Django 3.2 on 2021-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0089_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='affiliate_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_commission_spent',
            field=models.FloatField(default=0),
        ),
    ]
