# Generated by Django 3.2 on 2021-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0090_auto_20210412_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_order_amount',
            field=models.FloatField(default=0),
        ),
    ]
