# Generated by Django 3.2 on 2021-07-27 13:15

from django.db import migrations, models
import nova_dash.models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_dash', '0094_auto_20210520_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=nova_dash.models.current_time),
        ),
    ]
